config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root "books#index"

  get 'ajax_search_books', to: 'books#ajax_search_books'

  resources :books, only: [:index, :show, :destroy, :new, :create] do
    resources :reviews, only: [:create, :new, :index]
  end

  namespace :users do
    get 'information', to: 'information#information'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  protect_from_forgery with: :exception
 
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    if params[:search].present?
      @books = Book.where("title LIKE ?", "%#{params[:search]}%")
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "#{@book.title} deleted successfully!"
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.save
    redirect_to books_path, notice: "#{@book.title} created successfully!"
  end

  def ajax_search_books
    # Xử lý sự kiện tìm sách theo title hoặc content
    if params[:search].present?
      @books = Book.where("title LIKE ? OR content LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @books = Book.all
    end

    # Update lại list book với value search
    render json: {
      partial: (render_to_string partial: 'list_book', collection: @books, as: :book, layout: false)
    }
  end

  private

  def book_params
    params.require(:book).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        @review = Review.new(book_id: params[:book_id], content: params[:content])
        if @review.save
            ActionCable.server.broadcast("review_book_#{@book.id}", { review: @review.content })
        end

    end

    def new
        @review = Review.new
    end

    def index
        @book = Book.find(params[:book_id])
        @reviews = @book.reviews.order(created_at: :desc)
    end
end

app/controllers/users/information_controller.rb
module Users
  class InformationController < ApplicationController
    before_action :authenticate_user!
    
    def information
      @user = current_user
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
    class RegistrationsController < Devise::RegistrationsController
        before_action :configure_sign_up_params, only: [:create]
        before_action :configure_account_update_params, only: [:update]

        def update
            self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
            prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

            resource_updated = update_resource(resource, account_update_params)
            yield resource if block_given?
            if resource_updated
                set_flash_message_for_update(resource, prev_unconfirmed_email)
                bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

                sign_out current_user
                redirect_to new_user_session_path, notice: 'Profile updated successfully.'
            else
                clean_up_passwords resource
                set_minimum_password_length

                redirect_to edit_user_registration_path, alert: "Failed to update profile: #{resource.errors.full_messages.join(', ')}"
            end
        end

        protected

        def configure_sign_up_params
            devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
        end

        def configure_account_update_params
            devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
        end

        def after_update_path_for(resource)
            users_information_path
        end

        private

        def account_update_params
            params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :user_name)
        end
    end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def new; end

    def destroy
      sign_out current_user
      redirect_to root_path, notice: "Signed out successfully."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_list_book.html.slim
tr
  td = book.title
  td = book.content
  td = link_to "Detail", book_path(book.id), class: "btn btn-info"
  td = button_to "Delete", book_path(book.id), method: :delete, data: { confirm: "Do you want to delete #{book.title} book?" }, class: "btn btn-danger"

app/views/books/index.html.slim
.container.mt-3
  .row.justify-content-center
    .col-md-8
      - if user_signed_in?
        h4.text-center.text-success 
          i Welcome #{current_user.user_name} to Book Review App
      h1 List of Books
      = form_with url: books_path, method: :get, local: true, class: "mb-3" do
        .input-group
          = text_field_tag :search, params[:search], class: "form-control", id: "search-input", data: { url: books_path }, placeholder: "Search book ..."
          = submit_tag "Search", class: "btn btn-primary"

      .table-responsive
        table.table.table-striped
          thead
            tr
              th Title
              th Content
              th
              th
          tbody.list-book-content
            - @books.each do |book|
              = render "books/list_book", book: book
      = link_to "Add Book", new_book_path, class: "btn btn-primary"

app/views/books/new.html.slim
.container
    .row.justify-content-center
        .col-md-8
            h1 Create new Book
            = form_with model: @book, url: books_path, method: :post do |form|
                .form-group
                    = form.label :title
                    = form.text_field :title, class: "form-control"
                .form-group
                    = form.label :content
                    = form.text_area :content, class: "form-control"
                = form.submit "Create", class: "btn btn-success mt-3"

app/views/books/show.html.slim
.container
    .row.justify-content-center
        .col-md-8
            h1 = @book.title
            h3 = @book.content
            #review-book-list data-book-id=@book.id
                = render "reviews/index"
            = render "reviews/new"

app/views/home/index.html.slim
= link_to "Home", root_path, class: "btn btn-primary"

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse.bg-dark
  .container
    = link_to "Codecamp", root_path, id: "logo"
    nav
      ul.nav.navbar-right.navbar-nav.flex-row.align-items-center
        - if user_signed_in?
          li.mx-2
            = link_to "Information", users_information_path, class: "btn btn-info"
          li.mx-2
          = button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "btn btn-danger"
        - else
          li.mx-2
            = link_to "Login", new_user_session_path, class: "btn btn-success"
          li.mx-2
            = link_to "Sign up", new_user_registration_path, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Codecamp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_index.html.slim
- @reviews.each do |review|
  p = review.content

app/views/reviews/_new.html.slim
= form_with model: @review, url: book_reviews_path(@book), id: "review-form", method: :post do |form|
  = form.label :content
  = form.text_area :content, id: "input-review", class: "form-control"
  = form.submit "Create", id: "button-submit-review", class: "btn btn-success mt-3"

app/views/shared/_flash_messages.html.slim
- if notice
  .container-fluid.mt-2
    .alert.alert-success.alert-dismissible.fade.show role="alert"
      = notice
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

- if alert
  .container-fluid.mt-2
    .alert.alert-danger.alert-dismissible.fade.show role="alert"
      = alert
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/users/information/information.html.slim
.container.mt-3
  .row.justify-content-center
    .col-md-8
      .card.shadow
        .card-header.bg-info.text-white
          h3.mb-0.text-center User Information
        .card-body
          .row.mb-4
            .col-md-4
              .card
                .card-body.text-center
                  i.fas.fa-user.fa-3x.mb-3.text-primary
                  h5.card-title = @user.user_name
                  p.card-text.text-muted Member
          
          .row
            .col-md-12
              .card.mb-3
                .card-header.bg-light
                  h5.mb-0 User Details
                .card-body
                  .row.mb-3
                    .col-sm-4.text-muted Email:
                    .col-sm-8 = @user.email
                  .row.mb-3
                    .col-sm-4.text-muted Username:
                    .col-sm-8 = @user.user_name
                  .row.mb-3
                    .col-sm-4.text-muted Member Since:
                    .col-sm-8 = @user.created_at.strftime("%B %d, %Y")
              
              .card
                .card-header.bg-light
                  h5.mb-0 User Actions
                .card-body
                  .d-flex.justify-content-between
                    = link_to edit_user_registration_path, class: "btn btn-primary" do
                      i.fas.fa-edit
                      | Edit Profile
                    = link_to root_path, class: "btn btn-outline-secondary" do
                      i.fas.fa-home
                      | Back to Home